version: '3'
services:
    db:
        container_name: gnito_db
        image: mongo:7
        ports:
            - 27017:27017
    api:
        container_name: gnito_api
        build:
            context: ./server/api
        ports:
            - 3000:3000
        volumes:
            - ./server/api:/api
            - /api/node_modules
        depends_on:
            - db
        environment:
            - MONGO_URL=mongodb://db:27017/gnito
        command: npm start
    app:
        container_name: gnito_app
        build:
            context: ./client/app
        ports:
            - 8080:8080
        volumes:
            - ./client/app:/app
            - /app/node_modules
        depends_on:
            - api
        env_file: ./client/app/.env.dev
        command: npm run serve
